# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HkzaLyAvqF3c4NHdcBJ_sSQgTwIdjOLM
"""

from collections.abc import Sequence
from Bio import SeqIO
my_fasta=""">human_cox
ATGTTCGCCGACCGTTGACTATTCTCTACAAACCACAAAGACATTGGAACACTATACCTACTATTCGGCG
CATGAGCTGGAGTCCTAGGCACAGCTCTAAGCCTCCTTATTCGAGCCGAACTGGGCCAGCCAGGCAACCT
TCTAGGTAACGACCACATCTACAACGTTATCGTCACAGCCCATGCATTTGTAATAATCTTCTTCATAGTA
>dorsophila_cox
ACTCAGATCTGTCATACCCGTGTGAAAAGTAGCAAGAACAAGAAAAGCAGCATGTTGAGCATCACGGCCC
GTAACCTGGCAAGCGCCCTCCGCAGCAGCCTCGTCGGCACATCGTCGCGCGTGGCCGCCGTGCGCTGTCT
CGACGGAACCGAGGAATCGGCGGAGGAGTTCGACAAGCGCTACGAGAAGTACTTCAGCCGTGAGGGCATC
>zebra_fish
GTATTTGGTGCTTGAGCCGGAATAGTAGGGACCGCATTAAGCCTCTTAATCCGAGCTGAACTTACCCAAC
CAGGAGCACTTCTTGGTGATGATCAAATCTATAATGTTATTGTTACTGCCCATGCTTTTGTAATAATTTT
CTTTATAGTAATACCCATTCTTATTGGGGGATTTGGAAACTGACTTGTGCCACTAATGATTGGGGCCCCC"""

with open ('my_fasta',"w")as f:
  f.write(my_fasta)

with open('my_fasta',"r") as f:
  for record in SeqIO.parse(f,"fasta" ):
   print('protein',record.seq.translate()[::10])
   print("for 10 bases:",(record.seq[::10]))
   print('---')
   print('id:',record.id)
   print ("seq:",record.seq)
  print('---')

pip install biopython



ids=list(sequences.keys())

print(f"Comparing {ids[0]} and {ids[1]}: {match_percent(sequences[ids[0]], sequences[ids[1]])}%")
print(f"Comparing {ids[1]} and {ids[2]}: {match_percent(sequences[ids[1]], sequences[ids[2]])}%")
print(f"comparing {'human_cox and zebra_fish'}: {match_percent(sequences[ids[0]], sequences[ids[2]])}%")

ids=list(sequences.keys())
print(f"{match_percent(sequences[ids[0]],sequences[ids[2]])}%")

ids=list(sequences.keys())
print(f'comparing {ids[0]} and {ids[1]}: {match_percent(sequences[ids[0]],sequences[ids[1]])}%')





dna=('ATGTTC')
dna.count('A')