# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwfuiDZqDzPMrji7ytUyXgdxKAwl0jln
"""

Text='GCGCGGCGT'
Pattern='GCG'
def PatternCount(Text,pattern):
  count=0
  for i in range(len(Text)-len(Pattern)+1):
    if Text[i:i+len(Pattern)]==Pattern:
      count+=1
      return count

print(Pattern,PatternCount(Text,Pattern))

Text = 'GCGCG'
Pattern = 'GCG'
def CountOverlapping(Text,Pattern):
  count=0
  for i in range(len(Text)-len(Pattern)+1):

    window= Text[i:i+len(Pattern)]
    print(f'checking:{window} at index {i}')
    if window==Pattern:
     count  += 1

  return count

print('overlapping count:',CountOverlapping(Text,Pattern))

Text = 'GCGCG'
Pattern = 'GCG'

def CountOverlapping(Text,Pattern):
  count=0
  for i in range(len(Text)-len(Pattern)+1):
    if Text[i:i+len(Pattern)]:
      count+=  1


  return count

print('overlapping count:',CountOverlapping(Text,Pattern))

text='AAAATGTTTCCCTAAA'

startcodon='ATG'
stopcodon= ['TAA','TAG','TGA']
for i in range(len(text)-2):
  window=text[i:i+3]

  if window ==  startcodon:
    print(f'start codon at index{i}:{window}')
  elif window in stopcodon:
     print(f'stop codon at index{i}:{window}')


  codoon=text[i:i+3]
  print(f'codon at index{i}:{codoon}')

for i in range(0,3):

  codoon=text[i:i+3]
  print(f'codon at index{i}:{codoon}')

for i in range(0,len(text)):
   codoon=text[i:i+3]
   print(f'codon at index{i}:{codoon}')

for i in range(0,len(text),4):
 codoon=text[i:i+3]
 print(f'codon at index{i}:{codoon}')

dna='''ACTCAGATCTGTCATACCCGTGTGAAAAGTAGCAAGAACAAGAAAAGCAGCATGTTGAGCATCACGGCCC
GTAACCTGGCAAGCGCCCTCCGCAGCAGCCTCGTCGGCACATCGTCGCGCGTGGCCGCCGTGCGCTGTCT'''

start_codon='ATG'
stop_codon='TAA','TAG','TGA'

for i in range(len(dna)-2):
   codoon= dna[i:i+3]
   if codoon==start_codon:
    print('start codon:',codoon)

   elif codoon in stop_codon:
    print('stop_codon:', codoon)